from NN import Network
import numpy as np
import numpy.typing as npt
import activations as atv

#generated by AI for testing purposes.
def generate_house_price_data(
    num_samples: int = 100, 
    base_price: float = 50000.0, 
    price_per_sqft: float = 150.0, 
    sqft_min: int = 800, 
    sqft_max: int = 3500, 
    noise_factor: float = 10000.0, 
    seed: int = 42
) -> npt.NDArray[np.float64]:
    
    rng = np.random.default_rng(seed)
    
    # 1. Generate the 1D arrays just like before
    sqft = rng.integers(sqft_min, sqft_max, num_samples)
    ideal_price = price_per_sqft * sqft + base_price
    noise = rng.normal(0, noise_factor, num_samples)
    price = ideal_price + noise
    price = np.maximum(0, price) # Keep as float
    
    # 2. Stack them into a single (num_samples, 2) array
    #    as [price, sqft]
    data = np.stack([price, sqft], axis=1)
    
    return data.astype(np.float64)

def main():
    # 1. Generate the raw data
    data = generate_house_price_data(num_samples=300)
    
    # --- 2. Normalize the data (the "data side" fix) ---
    # Calculate mean and std deviation for each column
    # Use keepdims=True to make broadcasting easier
    data_mean = np.mean(data, axis=0, keepdims=True) # Shape (1, 2)
    data_std = np.std(data, axis=0, keepdims=True)   # Shape (1, 2)

    # Prevent division by zero if std is 0 (unlikely, but safe)
    data_std[data_std == 0] = 1 

    # Apply standardization: (data - mean) / std
    # This normalizes the 'price' and 'sqft' columns independently
    normalized_data = (data - data_mean) / data_std
    
    # ---------------------------------------------------

    # 3. Define network
    # Your [1, 1] network will now learn the relationship
    # between normalized_sqft and normalized_price
    layers = [1, 1]
    
    # Using ReLU as you specified. A linear activation might also be good.
    activations = [atv.Linear]

    network = Network(42, layers, activations)
    
    # 4. Train on the NORMALIZED data
    #    NOTE: The learning rate MUST be much smaller now.
    #    0.2 is far too large for normalized data and will "explode".
    #    A small LR like 0.001 is a much better starting point.
    network.train(normalized_data, 0.001, 100, 0.2)


if __name__ == '__main__':
    main()